### ISSUE TITLE
strange properties init behavior

### ISSUE THREAD

**Issue by redcloud80** [moobilejs/moobile-core#12]
<pre>
MyClass = new Class({
	Extends: Moobile.ViewController,

	myProperty: "cool"

	loadView: function() {
		this.view = Moobile.View.at('my-view.html');
		alert("1. " + this.myProperty);
	},

	viewDidLoad: function() {
		this.parent();
		alert("2. " + this.myProperty);
	},

	viewDidBecomeReady: function() {
		this.parent();
		alert("3. " + this.myProperty);
	}

});

var x = new MyClass();
x.myProperty = "fool";

var viewControllerStack = this.getViewControllerStack();
viewControllerStack.pushViewController(x, new Moobile.ViewTransition.Slide());
</pre>

the output is
1. cool
2. cool
3. fool

but I'm expecting the following output
1. fool
2. fool
3. fool

Is it a bug or what?

**Comment by YannickGagnon** [comment]
@redcloud80 It's the expected behavior.
